### ISSUE TITLE
Spin2 text not display on watch face

### ISSUE THREAD

**Issue by yukikwi** [novvember/amazfit-watchfaces#1]
Watch face applied but most text doesn't display on it.

![17194907460711619468778064766882](https://github.com/novvember/amazfit-watchfaces/assets/66879660/60ba1e2c-3591-45b6-a124-0ea4e974d7ef)

I also tried apply spin2 watchface from zepp official app (watch faces) and got same result.

Device: Amazfit gtr3
Firmware version: 7.47.5.1

**Comment by novvember** [comment]
Hi! Thank you for reporting the bug.

I looked into the details. The issue is that the watch face uses text with a custom font. This feature is supported in ZeppOS only starting from version 2.0. I found out that the GTR 3 watches have not received an update with this OS version. Therefore, all text information is not displayed.

I will try to find out how to remove this watch face from the official app store for this watch model.
